### ISSUE TITLE
`ERROR: Could not resolve "astro:db"` when running `astro dev`

### ISSUE THREAD

**Issue by frederickblaesing** [pilcrowOnPaper/lucia-adapter-astrodb#14]
Running `astro dev` reports an unhandled rejection as follows:
```
Astro detected an unhandled rejection. Here's the stack trace:
Error: Build failed with 1 error:
node_modules/lucia-adapter-astrodb/dist/index.js:2:24: ERROR: Could not resolve "astro:db"
    at failureErrorWithLog (node_modules/vite/node_modules/esbuild/lib/main.js:1651:15)
    at node_modules/vite/node_modules/esbuild/lib/main.js:1059:25
    at node_modules/vite/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

```json
{
  "astro": "^4.8.3",
  "lucia-adapter-astrodb": "^0.0.8",
  "@astrojs/db": "^0.10.7"
}

**Comment by pilcrowonpaper** [comment]
Did you follow the setup guide?

https://github.com/pilcrowOnPaper/lucia-adapter-astrodb?tab=readme-ov-file#setup

**Comment by frederick-blaesing** [comment]
Oops, I skipped the vite config. https://github.com/pilcrowOnPaper/lucia-adapter-astrodb/blob/ecefa40be925b877e4bdf22b833fae1ce601f2f2/README.md?plain=1#L14-L22
Thank you for pointing it out! Hopefully this Issue can still help others who encounter the same error.
